### ISSUE TITLE
RNG engine is statically declared in a header file. 

### ISSUE THREAD

**Issue by gitoliver** [GLYCAM-Web/gmml2#6]
// Seed with a real random value, if available
static pcg_extras::seed_seq_from<std::random_device> seed_source;
// Make a random number engine
static pcg32 rng(seed_source);

I don't think I've included it everywhere, but this is a bad idea.

**Comment by vraid** [comment]
It's now defined locally in the programs that use randomness; the glycoprotein builder and wiggle to site.
