### ISSUE TITLE
Preprocessing with water molecules creates strange connectivities between waters

### ISSUE THREAD

**Issue by gitoliver** [GLYCAM-Web/gmml2#7]
[0.RA9.pdb.txt](https://github.com/GLYCAM-Web/gmml2/files/14540558/0.RA9.pdb.txt)
If you compile test 019 and run it with this file you see in the off file that water molecules that are distance get connected:
 6871 6898 1
 7068 7069 1
I tried deleting the waters, but it just bonded a different pair of them. Visually they are far apart.

**Comment by vraid** [comment]
What's the visual distance between them? In the outputPdbFile i see

```
HETATM 6871 O    HOH L 594     -23.596  24.548 -46.676  1.00 52.12           O
HETATM 6898 O    HOH L 621     -22.617  25.659 -46.805  1.00 57.79           O
```
```
HETATM 7068 O    HOH H 791     -16.760  -4.926 -34.647  1.00 58.27           O
HETATM 7069 O    HOH H 792     -17.918  -4.109 -34.999  1.00 53.20           O
```

Which is a distance of 1.486 and 1.46, respectively, well within the max cutoff of 1.65.
This is running on a recent build, not the version of when this was posted.

**Comment by gitoliver** [comment]
I suspected this was a bug in the threaded code. So likely you've fixed it.
